using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LeftJudge : MonoBehaviour
{
    public GameObject thisObject;
    PuzulPlayerCon ppcon;
    GameObject puzulp;
    Collider2D thiscol;
    bool game,onWire;
    // Start is called before the first frame update
    void Start()
    {
        game = false;
    }

    public void Prepare()
    {
        puzulp = GameObject.Find("PuzulPlayer");
        ppcon = puzulp.GetComponent<PuzulPlayerCon>();
        game = true;
    }

    // Update is called once per frame
    void Update()
    {
        //Debug.Log(thiscol);

        if(game == true)
        {
            if (onWire == true)//Šî”Âã‚É‚¢‚é‚©‚Ç‚¤‚©Šm”F
            {
                if (thiscol.gameObject.tag == "Wire" || thiscol.gameObject.tag == "Initial" || thiscol.gameObject.tag == "Finish")//WireTag‚ÉG‚ê‚Ä‚¢‚é‚È‚ç“®‚¯‚é
                {
                    //Debug.Log("Wire‚ÉG‚ê‚Ä‚¢‚é‚Ì‚ÅA¶‚É“®‚¯‚Ü‚·");
                    ppcon.left = true;
                }
                else//WireˆÈŠO‚É‚¢‚é‚È‚ç“®‚¯‚È‚¢
                {
                    //Debug.Log("Wire‚ÉG‚ê‚Ä‚¢‚È‚¢‚Ì‚Å¶‚É‚Í“®‚¯‚Ü‚¹‚ñ");
                    ppcon.left = false;
                }
            }
            else//‚¢‚È‚©‚Á‚½‚ç–³ğŒ‚ÉˆÚ“®•s‰Â
            {
                //Debug.Log("left‚Í‰½‚É‚àG‚ê‚Ä‚¢‚È‚¢");
                ppcon.left = false;
            }
        }
    }

    private void OnTriggerEnter2D(Collider2D col)
    {
        onWire = true;
        thiscol = col;
    }

    private void OnTriggerStay2D(Collider2D col)
    {
        onWire = true;
        thiscol = col;
    }

    private void OnTriggerExit2D(Collider2D col)
    {
        onWire = false;
        thiscol = col;
    }
}
